import React, { useEffect } from 'react';

const Fireflies = () => {
  useEffect(() => {
    const container = document.getElementById('fireflies-container');
    if (!container) return;

    const fireflyCount = 30; // Number of fireflies

    for (let i = 0; i < fireflyCount; i++) {
        const firefly = document.createElement('div');
        firefly.classList.add('firefly');

        // Random positioning
        const left = Math.random() * 100;
        const top = Math.random() * 100;
        const animDuration = 10 + Math.random() * 20; // 10-30s
        const animDelay = Math.random() * 20;
        const scale = 0.5 + Math.random() * 0.5; // vary size slightly

        firefly.style.left = `${left}%`;
        firefly.style.top = `${top}%`;
        firefly.style.animationDuration = `${animDuration}s`;
        firefly.style.animationDelay = `-${animDelay}s`; // Start at random time in cycle
        firefly.style.transform = `scale(${scale})`;

        container.appendChild(firefly);
    }

    return () => {
        if(container) container.innerHTML = '';
    }
  }, []);

  return (
    <div id="fireflies-container" className="fixed top-0 left-0 w-full h-full -z-10 pointer-events-none overflow-hidden">
        {/* Fireflies generated by JS */}
    </div>
  );
};

export default Fireflies;
